### ISSUE TITLE
Request for Position - Unique ID for PWAs

### ISSUE THREAD

**Issue by philloooo** [mozilla/standards-positions#559] opened 2021-07-28 20:00 UTC
## Request for Mozilla Position on an Emerging Web Specification

* Base specification title: Web Application Manifest (https://www.w3.org/TR/appmanifest/)
* Proposal https://github.com/w3c/manifest/pull/988
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @marcoscaceres offered to implement this in Gecko

### Other information
This proposal explicitly defines what uniquely identifies a PWA and allow developers to specify the identifier in the manifest.

**Comment by marcoscaceres** [comment] 2021-09-22 08:50
Patch: https://phabricator.services.mozilla.com/D126331

**Comment by annevk** [comment] 2021-09-29 12:07
This is a duplicate of #493.

**Closed by annevk** 2021-09-29 12:07 UTC
