### ISSUE TITLE
Request for position on HTTP 103 Early Hints

### ISSUE THREAD

**Issue by bashi** [mozilla/standards-positions#530] opened 2021-05-19 00:48 UTC
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: HTTP 103 Early Hints
* Specification or proposal URL:  https://datatracker.ietf.org/doc/html/rfc8297
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

Fastly's blog post which describes the motivation:
https://www.fastly.com/blog/beyond-server-push-experimenting-with-the-103-early-hints-status-code

**Comment by annevk** [comment] 2021-05-19 09:15
This is a duplicate of #134:

> We believe that experimentation with the 103 response code is worthwhile, while at the same time noting that its primary benefit comes from using it with `rel=preload`, which Firefox does not yet implement. We do have some concerns about the lack of clear interaction with Fetch, which we hope will be specified before the mechanism is put into widespread use.

I suppose we should update that as we implement some form of `rel=preload` now I think. The other concerns stand (but per blink-dev will be addressed as I understand it).

cc @ddragana

**Comment by ddragana** [comment] 2021-05-19 09:24
I will add a comment to #134

**Comment by ddragana** [comment] 2021-05-19 09:25
We can close this issue as a dup of #134

**Closed** 2021-05-19 09:30 UTC
Labels: ietf, whatwg
