### ISSUE TITLE
Request for linear() easing function

### ISSUE THREAD

**Issue by danielsakhapov** [mozilla/standards-positions#747] opened 2023-02-15 15:25 UTC
* Specification Title: the linear easing function
* Specification or proposal URL (if available): https://w3c.github.io/csswg-drafts/css-easing/#the-linear-easing-function

### Other information

I see Firefox has this implemented behind the flag, but the test(https://wpt.fyi/css/css-easing/linear-timing-functions-syntax.tentative.html) says that linear() and linear(0) should set the property, which isn't correct as per spec:

> If there are less than two [items](https://infra.spec.whatwg.org/#list-item) in stopList, then return failure.

Would you consider fix this? Also, what are your thoughts on the state of the spec?

**Comment by CanadaHonk** [comment] 2023-02-15 17:08
Possible duplicate of https://github.com/mozilla/standards-positions/issues/649 ?

**Comment by CanadaHonk** [comment] 2023-02-15 18:23
Firefox and WPT bug now have a patch: https://phabricator.services.mozilla.com/D169955

**Comment by martinthomson** [comment] 2023-02-16 00:15
Yes, this is a duplicate.  Please take up any issues with tests or specification on their respective repositories.

**Closed by martinthomson** 2023-02-16 00:15 UTC
