### ISSUE TITLE
ImportMap Support

### ISSUE THREAD

**Issue by SamuelJohnsonMedia** [mozilla/standards-positions#501] opened 2021-03-14 21:16 UTC
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: ImportMap
* Specification or proposal URL: https://wicg.github.io/import-maps/
* Caniuse.com URL (optional): https://caniuse.com/?search=importmap

### Other information

There has been a bit of discussion about this on Twitter, mostly from David Heinemeier Hansson from Basecamp; it would be great to get Mozilla's position on this (apologies if this has been discussed but I could not find anything on the site or the web):
https://twitter.com/dhh/status/1352227465251459073

WICG proposal:
https://github.com/WICG/import-maps/blob/master/README.md#the-basic-idea

**Comment by annevk** [comment] 2021-03-15 06:33
Duplicate of #146. It's already on the dashboard: https://mozilla.github.io/standards-positions/#import-maps.

**Closed by annevk** 2021-03-15 06:33 UTC
