### ISSUE TITLE
Writing Assistance APIs

### ISSUE THREAD

**Issue by MrBrain295** [mozilla/standards-positions#1102] opened 2024-10-19 14:19 UTC
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Writing Assistance APIs
* Specification or proposal URL (if available): N/A
* Explainer URL (if available): https://github.com/WICG/writing-assistance-apis/blob/main/README.md
* Proposal author(s) (`@`-mention GitHub accounts): @domenic 
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional):
* WebKit standards-position: https://github.com/WebKit/standards-positions/issues/393

**Comment by domenic** [comment] 2024-10-20 06:55
Dupe of https://github.com/mozilla/standards-positions/issues/1067 I think :)

**Closed** 2024-10-20 15:27 UTC
