### ISSUE TITLE
Request for position update on Web Serial with add-on gating

### ISSUE THREAD

**Issue by Merlin04** [mozilla/standards-positions#847] opened 2023-07-13 17:30 UTC
I'd like to request an update on Mozilla's position on Web Serial. Web MIDI [has been implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=836897) for around 7 months now, and it's an API which carries very similar security implications to Web Serial (unrestricted communications with arbitrary hardware devices over a specific channel, of which implications are difficult to communicate to users). The Firefox Web MIDI implementation's solution of add-on gating solves this problem by presenting a flow which (simplifying here) conveys a similar granting of access as one would give when installing software, thus adequately getting informed consent from the user. 

With this solution having been deployed and battle-tested for a substantial amount of time, I'd like to request that Mozilla reconsider its position on Web Serial (assuming an add-on gate like Web MIDI).

**Comment by nschonni** [comment] 2023-07-13 17:40
Duplicate of https://github.com/mozilla/standards-positions/issues/687

**Comment by tantek** [comment] 2023-07-13 19:46
Thanks @nschonni. Closing as duplicate of #687. @Merlin04 please go ahead and make your comment regarding add-on gating on that issue.

**Closed by tantek** 2023-07-13 19:46 UTC
Labels: invalid

**Comment by Merlin04** [comment] 2023-07-13 20:04
Done, sorry for the duplicate.
