### ISSUE TITLE
CSS `@starting-style`

### ISSUE THREAD

**Issue by nileshprajapati** [mozilla/standards-positions#1007] opened 2024-04-03 14:58 UTC
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: CSS Transitions Level 2
* Specification or proposal URL (if available):  https://drafts.csswg.org/css-transitions-2/#defining-before-change-style
* Explainer URL (if available):
* Proposal author(s) (`@`-mention GitHub accounts): 
* Caniuse.com URL (optional):  https://caniuse.com/mdn-css_at-rules_starting-style
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

Safari 17.5 Beta Release Notes: https://developer.apple.com/documentation/safari-release-notes/safari-17_5-release-notes
Chrome: Shipped in 117.

**Comment by zcorpan** [comment] 2024-04-04 09:38
Duplicate of https://github.com/mozilla/standards-positions/issues/833

**Closed by zcorpan** 2024-04-04 09:38 UTC
