### ISSUE TITLE
PWAs as URL Handlers

### ISSUE THREAD

**Issue by LuHuangMSFT** [mozilla/standards-positions#550] opened 2021-07-07 21:27 UTC
## Request for Mozilla Position on an Emerging Web Specification

* Base specification title: Web Application Manifest (https://www.w3.org/TR/appmanifest/)
* Specification or proposal URL: explainer at https://github.com/WICG/pwa-url-handler/blob/main/explainer.md 
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information
This work targets the "Web Application Manifest" spec by recognizing "url_handlers" as a valid field. It also aims to add a "Web App Origin Association" spec. as a supplement to the "Web Application Manifest" spec.

More links and documentation can be found at: https://www.chromestatus.com/feature/5739732661174272
Article with descriptions of developer and user experiences: https://web.dev/pwa-url-handler/

(Note: this request's proposal is different from the one in #340.)

**Comment by nschonni** [comment] 2021-07-07 22:27
Think this is a duplicate of https://github.com/mozilla/standards-positions/issues/340

**Comment by LuHuangMSFT** [comment] 2021-07-07 22:56
@nschonni @340 is about custom protocol URLs (eg.: mailto:Jane.Doe@example.com). (See https://web.dev/url-protocol-handler/). Both features are being developed in Chromium currently.

**Comment by martinthomson** [comment] 2021-08-13 01:05
Hi @LuHuangMSFT, Mozilla is currently not investing in PWAs. That's the reason for the delay and for why we're going to have to `defer` this request.

**Comment by LuHuangMSFT** [comment] 2021-08-31 19:47
Understood. Thanks!

**Closed** 2024-10-18 13:56 UTC
Labels: position: defer
